### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by persello** [WWDCScholars/WWDCScholars-form#13]
The Discord link in the "Thanks for joining" page of the form seems to be broken.
<img width="1436" alt="Schermata 2021-06-01 alle 14 56 06" src="https://user-images.githubusercontent.com/45900950/120326915-80436100-c2e9-11eb-8443-97855f58b5c5.png">
If I try to paste it in-app, it tells me that it might be invalid or expired.

**Comment by moritzsternemann** [comment]
Thanks for bringing this to our attention @persello! In the meantime you can use https://wwdcscholars.com/discord 😄
