### ISSUE TITLE
A couple of small grammar/spelling adjustments

### ISSUE THREAD

**Issue by Andrew-Walker** [WWDCScholars/WWDCScholars-form#5]
Spelling

**BEFORE**
"// This site is not affliates with Apple, Inc. but is made by a group of WWDCScholars who wants to inpire more people to learn how to code."

**AFTER**
"// This site is not affiliated with Apple, Inc. but is made by a group of WWDCScholars who want to inspire more people to learn how to code."

Also, could we remove the spaces between certain syntax (to be a bit more 'Swifty') such as...

**BEFORE**
print ( "Hello, Scholars!" )
addYourselfIn ( Batch2016 , Batch2015 , Batch2014 , Batch2013 , Batch2012 , BatchEarlier ) 

**AFTER**
print("Hello, Scholars!")
addYourselfIn(Batch2016, Batch2015, Batch2014, Batch2013, Batch2012, BatchEarlier)

Finally, we do have a shared email address now. Up to you if you want to use it - wwdcscholars@gmail.com 😄

**Comment by michieriffic** [comment]
@Andrew-Walker corrected the grammar mistake already as pointed by Lukas. But didn't deploy yet on join.wwdcscholars.com

I will update the spaces. 

And I can definitely use that as the email. We should set autoforward to everyone in case of anything. We can also set our own email address in eg. team@wwdcscholars.com - this can easily be set up by @Oliver-Binns

**Comment by Andrew-Walker** [comment]
Ah, yeah. I saw that just after I posted this. I don't think Lukas mentioned changing 'affiliates' to 'affiliated' though.

**Comment by michieriffic** [comment]
Oh I didn't see that. Let me correct it again.

**Comment by michieriffic** [comment]
Done! @Andrew-Walker
Let's wait for @Oliver-Binns to deploy on his server. Temporarily I will deploy on heroku. 

Are you cool setting up a team@wwdcscholars.com email to make it even look professional?

**Comment by michieriffic** [comment]
You can check latest changes here. https://wwdcscholars.herokuapp.com

**Comment by michieriffic** [comment]
I have created a team@wwdcscholars.com email. Will send details later.

**Comment by Andrew-Walker** [comment]
Awesome, sounds good! Thanks for sorting that.

**Comment by michieriffic** [comment]
@Andrew-Walker When I was building the post form, i realised that we should use "wants" instead of "want" because I mentioned "a group of WWDCScholars" instead of just "WWDCScholars" :) So the noun "group" is singular.
